### ISSUE TITLE
port and host are hardcoded

### ISSUE THREAD

**Issue by fidelram** [Novartis/cellxgene-gateway#12]
Although is possible to provide the env variable: `GATEWAY_HOST`

port and ip are ignored and seen in line: https://github.com/Novartis/cellxgene-gateway/blob/master/cellxgene_gateway/gateway.py#L235

**Comment by alokito** [comment]
Hello @fidelram! Thank you for your comment. The GATEWAY_HOST is the hostname and port from  the perspective of the web browser, not the port that the gateway will bind to. These should be the same when there is no load balancer in between, and perhaps that is a common case.

I would like to stick with the convention of configuration via environment variables. Currently the GATEWAY_HOST and GATEWAY_PROTOCOL are really aspects of the load balancer, not really of the gateway itself. They are primarily used to build urls from the browser perspective during rewriting of content from the Cellxgene Server. So perhaps the best strategy would be as follows: 

- Introduce a GATEWAY_PORT, an open environment variable that defines the port the gateway will bind to, defaults to 5005
- Rename GATEWAY_HOST to GATEWAY_BROWSER_HOST and make it optional with default value "localhost:{GATEWAY_PORT}"
- Rename GATEWAY_PROTOCOL to GATEWAY_BROWSER_PROTOCOL and make it optional with default value "http"
- make GATEWAY_IP optional, default to `socket.gethostbyname(socket.gethostname())` 

That way the only required variables are CELLXGENE_DATA and CELLXGENE_LOCATION

**Comment by alokito** [comment]
For the GATEWAY_HOST and GATEWAY_PROTOCOL, I will introduce EXTERNAL_HOST and EXTERNAL_PROTOCOL, as I think that is more accurate.

**Comment by alokito** [comment]
@fidelram  this should be fixed, please let me know if there are any issues.

**Comment by fidelram** [comment]
Thanks! I will take a look
