### ISSUE TITLE
Enable local annotations

### ISSUE THREAD

**Issue by alokito** [Novartis/cellxgene-gateway#14]
https://chanzuckerberg.github.io/cellxgene/posts/annotations

**Comment by Jon-bioinfo** [comment]
cellxgene v0.15.0 makes annotations on by default and changes some command line params for this. https://github.com/chanzuckerberg/cellxgene/releases/tag/0.15.0
Will this be compatible with cellxgene-gateway?

Thanks!

**Comment by alokito** [comment]
It will be... The annotation support currently implemented in master is only compatible with Cellxgene 0.14.0... perhaps I should publish a version to pypi before updating the annotation support since it is a breaking change.
