### ISSUE TITLE
Data order change

### ISSUE THREAD

**Issue by GHAStVHenry** [Novartis/cellxgene-gateway#19]
File crawler order appears to be based on created time?

Anyway to get the option to order alphabetically?

**Comment by GHAStVHenry** [comment]
appears to be a result of `all_entries = os.listdir(path)` which I believe orders based on indexing on the filesystem

`all_entries = sorted(os.listdir(path))`  should work?

**Comment by alokito** [comment]
The order was not defined before. I am happy to default to alphabetic, if we want more options I'll add an environment variable or something.
