### ISSUE TITLE
cellxgene 0.16.0 breaks cellxgene-gateway

### ISSUE THREAD

**Issue by GHAStVHenry** [Novartis/cellxgene-gateway#24]
Just an FYI... I'm going to try and find some time to deep-dive this, but maybe y'all can find the problem quicker?

**Comment by alokito** [comment]
I (probably) won't have time to look at this until the weekend.

**Comment by alokito** [comment]
@GHAStVHenry  the issue turned out to be some new absolute paths that needed to be rewritten. I have made a PR with a fix, please confirm it works and I will merge: https://github.com/Novartis/cellxgene-gateway/pull/27

**Comment by GHAStVHenry** [comment]
Confirmed... it works... thank you so much for looking at this so soon!!!
