### ISSUE TITLE
Add ability to pass command line args to Cellxgene

### ISSUE THREAD

**Issue by simoond** [Novartis/cellxgene-gateway#25]
Example: 

if I want to launch Cellxgene using the following command args

--disable-diffexp 
--disable-annotations 
--max-category-items 500 

This could be implemented using just one env variable such as "CELLXGENE_ARGS" perhaps?

Thanks

**Comment by alokito** [comment]
@simoond feel free to weigh in on the PR, if I don't hear back I'll likely merge in a day or so.

**Comment by alokito** [comment]
Released in version 0.2.1.

**Comment by Bhersbach** [comment]
When I specify --disable-annotations through CELLXGENE_ARGS in the environment by using export CELLXGENE_ARGS=--disable-annotations, the server still prompts me for a user generated directory to store annotations. Am I missing something?
