### ISSUE TITLE
cellxgene  gateway fails to launch cellxgene

### ISSUE THREAD

**Issue by wariobrega** [Novartis/cellxgene-gateway#29]
Hello everyone, 

I am trying to use your software to put online a series of .h5ad files for my lab.

I have created a separate conda environment to run cellxgene gateway and followd the installation instruction, plus a put a bunch of .h5ad files in a custom directory.

the files are correctl seen by cellxgene-gateway. However, when I attempt to open them, I obtain the following error:

![image](https://user-images.githubusercontent.com/10073781/92158672-9096e000-ee2c-11ea-943f-942659e70d93.png)

The cellxgene gateway stays up, but the port into which is running (5005) goes offline.

On my command shell, I instead obtain the following error messages:
![image](https://user-images.githubusercontent.com/10073781/92158981-f71bfe00-ee2c-11ea-9ee0-de4bb6a7cc28.png)

Can you help me figure out what is happening?

Thanks a lot,

Daniele

**Comment by wariobrega** [comment]
I found the problem, my environment was running python 3.8.5 and when I switched to python 3.7 it worked.

Thanks anyways and I hope this helps you!

**Comment by alokito** [comment]
Hi @wariobrega, thanks for taking the time to open a ticket! I just tested, and cellxgene-gateway seems to work fine with python 3.8. From the screenshot you have provided, I think there may have been a separate issue. The command line to launch cellxgene looks like:

> which cellxgene launch /home/caposquared....

It should really have a complete path to cellxgene, not the which command. In the readme it suggests to use backticks, which run the command "which cellxgene" and return a complete path:

> export CELLXGENE_LOCATION=`which cellxgene`

I suspect you may have used double or single quotes, which will return the literal string "which cellxgene":

> export CELLXGENE_LOCATION='which cellxgene'

Glad you were able to get it working.
