### ISSUE TITLE
GATEWAY_ENABLE_ANNOTATIONS does not enable annotations

### ISSUE THREAD

**Issue by wariobrega** [Novartis/cellxgene-gateway#30]
hello,

I managed to run cellxgene-gateway on my local server. 

Everything seems to work fine except for the `GATEWAY_ENABLE_ANNOTATIONS `variable. I set it to `1` in order to enable annotations. Additionally, I passed the --annotations-dir (with a valid path) to the `CELLXGENE_ARGS` variable. 

When I launch cellxgene-gateway I see that `GATEWAY-ENABLE-ANNOTATIONS` is set to `True`.

however, each cellxgene process is running with the `--disable-annotations` flag (`--annotations-dir` is passed correctly).

For the record, I'm running the tool into a conda environment and cellxgene version is 16.04.

Glad if you could provide any help on this.

Daniele

**Comment by alokito** [comment]
Hi @wariobrega, thanks for taking the time to ask this question! I am not sure exactly what behavior you are seeing. When GATEWAY_ENABLE_ANNOTATIONS is True, cellxgene-gateway allows you to open files with named annotation collections. If you click the file name, it will be opened without annotations, which I think is the behavior you are seeing. If you click "new", it will prompt you for an annotation collection name as follows:

![clickNew](https://user-images.githubusercontent.com/789030/92414433-2fb82200-f122-11ea-83d8-f0b6cc960684.png)

Later, when you reload the file crawler page, it will show all the existing annotation collections. You can click an existing collection to view/edit, or click "new" to add another one: 

![withCollection](https://user-images.githubusercontent.com/789030/92414519-98070380-f122-11ea-816d-c50e7f00c4e9.png)

Also, when setting GATEWAY_ENABLE_ANNOTATIONS=True you should probably not set --annotations-dir in CELLXGENE_ARGS, as cellxgene-gateway manages the annotation file locations and this could create a conflict. I hope this helps.

**Comment by wariobrega** [comment]
Hi @alokito,

Thanks for your kind reply.

My apologies, I thought that the annotations would pop up directly as in the "standard cellxgene annotation" (so when opening the cellxgene, you would be prompted for an annotation file name etc.), plus the "--disable-annotations" feature was getting me confused.

I removed the cellxgene additional args and kept only the GATEWAY_ENABLE_ANNOTATIONS set to True. 

When I click on new annotation, I get a 404 error message though (see screenshot attached).

![image](https://user-images.githubusercontent.com/10073781/92458452-b3771a80-f1c5-11ea-8179-ba0c835643b5.png)


Am I missing something?

This is the log of what happens when I try to click on "new" in the background:

![image](https://user-images.githubusercontent.com/10073781/92458370-93475b80-f1c5-11ea-9b87-d069bd49e0f4.png)

Sorry if these questions seems too naive, I don't have a lot of experience in this field.

Cheers,

Daniele

**Comment by alokito** [comment]
There was a small bug fix in v0.2.1 to address a similar issue, which version of Cellxgene Gateway are you running? You can check with
`python -c 'import cellxgene_gateway; print(cellxgene_gateway.__version__)'`

**Comment by wariobrega** [comment]
I am running version 0.2.1 (just re-checked) , pulled from git a week ago or so through pip

**Comment by alokito** [comment]
Doh! I have replicated the issue, and should have time to fix later this evening. Thanks for reporting.
I should also implement some proper regression tests.

**Comment by wariobrega** [comment]
no worries, let me know when it works and I'll test it ;)

**Comment by alokito** [comment]
This issue should be fixed in v0.2.2, please give it a try when you have some time and let me know how it goes.

**Comment by wariobrega** [comment]
It works as a charm! Perfect! thanks a lot @alokito!
