### ISSUE TITLE
Production deployment 

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [Novartis/cellxgene-gateway#33]
Hi, 

Thank you for developing the application! `cellxgene-gateway` deploys the browser in development; how to deploy this on production server?

Thanks!
Parul

**Comment by alokito** [comment]
Hi Parul, there are a number of production quality WSGI servers including Gunicorn that you could try. To be honest, I have been running with the flask test server in production without many issues. However, it looks like some people are using reverse proxies such as nginx plus production WSGI servers, so I should probably explore more of these configurations to provide better support.

**Comment by Parul-Kudtarkar** [comment]
Thank you @alokito, I'll keep you posted!

**Comment by alokito** [comment]
@Parul-Kudtarkar  any updates? I'm going to close for now.
