### ISSUE TITLE
0.2.3 csv create URL issue

### ISSUE THREAD

**Issue by Jon-bioinfo** [Novartis/cellxgene-gateway#43]
I'm setup with a reverse proxy and version 0.2.2 had no issue, after upgrading to 0.2.3 I have an error when I try to create a new annotation, loading existing annotations seems fine.

```
export CELLXGENE_LOCATION=/home/jonathan/venv/main/bin/cellxgene
export CELLXGENE_DATA=/data/cellxgene_data
export EXTERNAL_HOST='my.url.com'
export EXTERNAL_PROTOCOL='https'
export GATEWAY_ENABLE_ANNOTATIONS=true
export GATEWAY_ENABLE_BACKED_MODE=true

cellxgene-gateway

cellxgene_gateway:INFO:launching yes | /home/jonathan/venv/main/bin/cellxgene launch /data/cellxgene_data/10x/pbmc3k.h5ad --port 8010 --host 127.0.0.1 --annotations-file /data/cellxgene_data/10x/pbmc3k_annotations/test2.csv --backed
werkzeug:INFO:IP - - [26/Mar/2021 09:51:38] "GET /view/10x/pbmc3k_annotations/test2.csv HTTP/1.1" 302 -
2021-03-26 09:51:38,687:werkzeug:ERROR:IP- - [26/Mar/2021 09:51:38] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x83\x1dú\x84¢ Fd\x8b¿\x88\x1f»\x14\x05{³\x15É\x17\x8e-BMåÿPÃ¸\x03²ú ^\x8b£)\\ou«²W\x11\x8b3à\x87_ês')
2021-03-26 09:51:38,687:werkzeug:INFO:IP- - [26/Mar/2021 09:51:38] "üú¢ Fd¿»{³É-BMåÿPÃ¸²ú ^£)\ou«²W3à_ês" HTTPStatus.BAD_REQUEST -
2021-03-26 09:51:38,714:werkzeug:ERROR:IP- - [26/Mar/2021 09:51:38] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03m2Ó\x10äèQõQÊ\x1a\x1a°¬Æ;\x19¢"\x00û <1UUû\x8eÖTk- àb¢ö\x97Ùçe]\x98\rR*7!\x0b\x98\t*ÁZw\x96j¯Æ§Ø\x8d¼')
R*7!-03-26 09:51:38,714:werkzeug:INFO:IP- - [26/Mar/2021 09:51:38] "üm2ÓäèQõQÊ°¬Æ;¢"û <1UUûÖTk- àb¢öÙçe
```

**Comment by alokito** [comment]
Hi Jon,

I am unfortunately not able to reproduce this issue. The main change in 0.2.3 was introducing support for the PROXY_FIX variables and a related move to using url_for to make urls rather than constructing them with string manipulation. It's not obvious to me how these could be causing the issue. Can you provide more details, for example which reverse proxy and roughly how it is configured?

**Comment by Jon-bioinfo** [comment]
Thanks for investigating, I did some googleing and saw similar errors related to http/https https://github.com/samuelclay/NewsBlur/issues/642#issuecomment-541338423

changing to `export EXTERNAL_PROTOCOL='http'` fixed this issue. 
I'm not sure how the reverse proxy is setup, it was done by our sysadmin. My url is https but I guess this is being handled by the proxy and doesn't need to be set in cellxgene-gateway.

**Comment by alokito** [comment]
Hi Jon, thanks for following up. EXTERNAL_PROTOCOL (more properly GATEWAY_PROTOCOL) is only used to set the  "wsgi.url_scheme" environment variable in v0.2.3. In v0.2.2, it was used for that as well as constructing urls that are now produced using url_for. I am not sure how this is related to the issue.

**Comment by Jon-bioinfo** [comment]
This issue is reproducible for me flipping http and https in EXTERNAL_PROTOCOL.
When it is set to https creating a new annotation is redirected to `https://server_name.domain:5005/view/10x/pbmc3k_annotations/test02.csv/` (the EXTERNAL_HOST is not being used)
But when I set http the url is being constructed properly as `https://external_host/view/10x/pbmc3k_annotations/test02.csv/`

**Comment by alokito** [comment]
Ah, that suggests a possible explanation. Perhaps when the "wsgi.url_scheme" is set to the same as the backend server (in this case http) the flask url_for method constructs relative paths, which then get interpreted by the browser as using the proper protocol and server. However, when the "wsgi.url_scheme" is different, it must construct absolute paths, which it does incorrectly. 

In fact, external_host is not used at all in the current code. I think I need to understand better how WSGI interacts with reverse proxies. In light of 0.2.3, I think the best way forward may bet to forget about setting EXTERNAL_HOST and EXTERNAL_PROTOCOL, and instead focus on the proxy fix variables, PROXY_FIX_HOST and PROXY_FIX_PROTO, which will take the host and protocol from the headers set by the proxy. In the short run I guess if it isn't broke then no need to fix it. Nevertheless I will try to find some time in the coming weeks to investigate further.
