### ISSUE TITLE
CELLXGENE_BUCKET subdir

### ISSUE THREAD

**Issue by GHAStVHenry** [Novartis/cellxgene-gateway#45]
subdir gets printed in h5ad filename and it says it couldn't find the item and lists the subdir twice
![image](https://user-images.githubusercontent.com/38675268/115325472-49f2bd80-a151-11eb-94d9-cf06d1241d56.png)

![image](https://user-images.githubusercontent.com/38675268/115325502-58d97000-a151-11eb-8b05-eb925bfa4c28.png)

if I have multiple nested subdirs... cellxgene-gateway fails to run with a exception S3 url doesn't exist and lists the first subdir twice in the exception...
getting: `Exception: S3 url 's3://XXX/PublishedData/PublishedData/2018CellReports' does not exist.`

The "PublishedData" folder only exists once...

**Comment by alokito** [comment]
Hi @GHAStVHenry ! Thanks for the bug report. I have checked in a fix on the "nested_s3" branch... I want to do a bit more testing before I make a bugfix release, but if you have time please give it a try.

**Comment by alokito** [comment]
Okay, I released 0.3.2, @GHAStVHenry  please give it a try so we can close this ticket.

**Comment by GHAStVHenry** [comment]
sorry, I didn't see your reply... I will test the release!

**Comment by GHAStVHenry** [comment]
Sorry again for the delay... confirmed nested dir bug has been fixed!!!

THANKS
