### ISSUE TITLE
Integrating cellxgene-gateway and cellxgene_VIP

### ISSUE THREAD

**Issue by PolinaPavlovich** [Novartis/cellxgene-gateway#52]
Hello,

Thank you for developing this beautiful software. Is there any way to combine cellxgene-gateway and cellxgene_VIP?

Best wishes,
Polina

**Comment by alokito** [comment]
Yes! It's pretty easy. You first install cellxgene-gateway, and then install cellxgene VIP in the same venv or conda environment. Then when cellxgene-gateway goes to launch cellxgene it will use the VIP version. We do this all the time, in fact the VIP version is more popular than the regular version of cellxgene.
