### ISSUE TITLE
incompatible numpy versions

### ISSUE THREAD

**Issue by alokito** [Novartis/cellxgene-gateway#55]
On a fresh install of cellxgene-gateway, I get the following error:

ERROR: numba 0.54.0 has requirement numpy<1.21,>=1.17, but you'll have numpy 1.21.2 which is incompatible.

However, if I install celllxgene version 0.18.0, and then upgrade to cellxgene 0.19.0, it seems to work. This is because numba is downgraded to 0.52.0 by this process. Thus a current workaround would be to downgrade numba to 0.52.0

**Comment by alokito** [comment]
I don't think there's anything to do here with cellxgene-gateway, as it is an issue with cellxgene itself, but I will leave it here.

**Comment by ericmjl** [comment]
Perhaps an alternative might be to pin numba at 0.52.0 explicitly in `requirements.txt`?

**Comment by alokito** [comment]
Sounds reasonable @ericmjl. Only potential downside would be if newer versions of cellxgene actually require numba 0.54.0 or later. I am a little hesitant to try and correct for issues in a dependency by locking down versions in my own repo. Really cellxgene should be handling this, and might already in the 1.0.0 release.

**Comment by alokito** [comment]
So... on a fresh install of cellxgene, I now get numba-0.54.1 and numpy-1.21.5 on a fresh install, which continues to print out the error during install: 

ERROR: numba 0.54.1 has requirement numpy<1.21,>=1.17, but you'll have numpy 1.21.5 which is incompatible.

and then if you run a simple `cellxgene --version` it errors out with

pkg_resources.ContextualVersionConflict: (numpy 1.21.5, Requirement.parse('numpy<1.21,>=1.17'), {'numba'})

So... I think it's best to report this as a bug to CZI.

**Comment by alokito** [comment]
https://github.com/chanzuckerberg/cellxgene/issues/2477

**Comment by alokito** [comment]
@AaronNHart I was able to resolve this issue by upgrading pip within the venv before installing cellxgene:
```
pip install --upgrade pip
```
Please take a look at the thread on chanzuckerberg/cellxgene#2477 for details. Does this help in your case as well?

**Comment by AaronNHart** [comment]
I don't have time to check just at the moment, but reading that comment I am 99% sure that was the issue.  I will report back if that's not the case.  Feel free to close the issue, thanks!
