### ISSUE TITLE
Is there a way to save an analysis state?

### ISSUE THREAD

**Issue by Matthew1309** [Novartis/cellxgene-gateway#56]
Hello, I like your gateway. I was wondering if there was a way to save the state of an analysis, not just gene sets I have created. (Or is this a question to ask at the cellxgene github?) Thank you in advance.

Edit: I also can't seem to find a way to save a selected subset of cells, that seems like it would be a nice feature.

**Comment by alokito** [comment]
I believe your first question is better addressed by the cellxgene github. I don't think there is a way to open a file to a particular state of analysis.
Regarding the second question, if you create  a custom annotation (which is equivalent to labeling a selected subset of cells) it is saved as an easily-parsed CSV file. Here are the example contents of a cell-labels file based on the example pbmc3k.h5ad dataset:
```
# Annotations generated on 2021-11-14T10:32:35 using cellxgene version 1.0.0
# Input data file was pbmc3k.h5ad, which was last modified on 2021-11-14T10:28:23
index,category_56
AAACATACAACCAC-1,unassigned
AAACATTGAGCTAC-1,unassigned
AAACATTGATCAGC-1,unassigned
AAACCGTGCTTCCG-1,unassigned
AAACCGTGTATGCG-1,unassigned
AAACGCACTGGTAC-1,unassigned
AAACGCTGACCAGT-1,unassigned
AAACGCTGGTTCTT-1,unassigned
AAACGCTGTAGCCA-1,unassigned
AAACGCTGTTTCTG-1,unassigned
AAACTTGAAAAACG-1,unassigned
AAACTTGATCCAGA-1,unassigned
AAAGAGACGAGATA-1,unassigned
AAAGAGACGCGAGA-1,mycells
AAAGAGACGGACTT-1,unassigned
AAAGAGACGGCATT-1,unassigned
AAAGCAGATATCGG-1,unassigned
AAAGCCTGTATGCG-1,unassigned
AAAGGCCTGTCTAG-1,unassigned
AAAGTTTGATCACG-1,unassigned
AAAGTTTGGGGTGA-1,unassigned
AAAGTTTGTAGAGA-1,unassigned
AAAGTTTGTAGCGT-1,mycells
```
