### ISSUE TITLE
Force update list of files without restarting server?

### ISSUE THREAD

**Issue by arogozhnikov** [Novartis/cellxgene-gateway#59]
Hello and thanks for a great tool.

I'm currently using our tool to display data in s3 folder.

In case when a new file is produced and uploaded to s3, the list of files is not updated and there is no way to display that data. Unfortunately, restarting gateway is non-trivial. Can you consider adding a button that would update the list of files? Thank you!

**Comment by alokito** [comment]
Hi @arogozhnikov ! It should be possible to efficiently check the more recent modification time for prefixes in S3 per https://stackoverflow.com/questions/36093875/how-to-check-when-is-the-last-time-s3-bucket-has-been-updated . I would like to try that first. Implementing an update button would complicate the user interface, as well as the internal interfaces of cellxgene-gateway.

**Comment by arogozhnikov** [comment]
@alokito  thank you, "?refresh=1" worked for me. 

Broader, I think it's more wise to just always pass refresh to ls, as listing of folder is very cheap and fast. 

Just as with FS, you ask listing each time, not cache locally folder contents. Does it make sense?

**Comment by alokito** [comment]
@arogozhnikov This should be addressed in v0.3.9, please confirm.

**Comment by arogozhnikov** [comment]
@alokito just tested and it works. Thank you so much for this tool!
