### ISSUE TITLE
Cannot install by any way

### ISSUE THREAD

**Issue by LuciaWL001** [Novartis/cellxgene-gateway#64]
Hi,
I tried the option 1 and 1 in Install Cellxgene-gateway setion, but cannot install due to AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'. 
Then I tried the Development install, and in the step 3 got the same error.
Please help to resolve it. Thank you~

**Comment by alokito** [comment]
Hi Lucia! This seems similar to issue #55. The solution there was to run `pip install --upgrade pip` after activating the venv, but before installing cellxgene-gateway. I found I also had to downgrade markupsafe with `pip install markupsafe==2.0.1` after installing cellxgene-gateway. I am not sure why python dependency management is such a headache! Let me know if this helps.
