### ISSUE TITLE
Suggestion: Put "new" annotation link at front of annotations list

### ISSUE THREAD

**Issue by Dane-Z** [Novartis/cellxgene-gateway#73]
Hello, your project is amazing and we've had success self-hosting with it internally. We're currently going through the code and adding some reformatting to the filecrawl page using filecrawl.html and filecrawl.py files. We are looking into how to reformat the item tree portion of the page. We might create many annotations for one data set so we'd like to put the "new" make annotation link to always appear at the front of the annotations list instead of the end

**Comment by alokito** [comment]
Hi @Dane-Z ! This is a fairly small change, and it's definitely doable. Also the position of the "new" is somewhat arbitrary and I haven't heard anyone wanting it a particular way. In our organization, the annotations feature has not been used much.

**Comment by alokito** [comment]
I made a pull request for this change, and plan to include it in the next release. I would also like to point out that you can get the old behavior back (or do something else) by overriding render_annotations like so:

```
from cellxgene_gateway.gateway import  main
from cellxgene_gateway import filecrawl, flask_util
from cellxgene_gateway.cache_key import CacheKey


def render_annotations(item, item_source):
    url = flask_util.view_url(
        item_source.get_annotations_subpath(item), item_source.name
    )
    new_annotation = f"<a class='new' href='{url}'>new</a>"
    annotations = (
        ", ".join(
            [
                f"<a href='{CacheKey(item, item_source, a).view_url}/'>{a.name}</a>"
                for a in item.annotations
            ]
        )
        + ", "
        if item.annotations
        else ""
    )
    return " | annotations: " + annotations + new_annotation

filecrawl.render_annotations = render_annotations
main()
```
I'm not sure if there's a "better" way to enable overriding in python.

**Comment by Dane-Z** [comment]
Thank you so much for this and the quick response! In addition, could you explain how to make the following changes to the itemtree? We are trying to figure out how to remove the "local" hyperlink and only show top level folders without subdirectories in a filecrawl page so that we can have a sort of "admin" top level view of all projects without showing the subdirectories. 
<img width="955" alt="image" src="https://user-images.githubusercontent.com/80366234/185953427-c2fbc51d-7924-4344-90cf-50c8a9a513fb.png">

**Comment by Dane-Z** [comment]
![image](https://user-images.githubusercontent.com/80366234/185953699-069778ee-2ae9-4786-a158-bb680e2e10ac.png)

**Comment by Dane-Z** [comment]
For anyone interested, I was able to achieve what I was going for using the code below. It's a bit rough but it works to show only top level directories if you have some sort of "admin" directory so that multiple projects can be viewed without their respective h5ad files (a more compact view of the folders/folder names). This is in fileitem_source.py.

def list_items(self, filter: str = None) -> ItemTree:
        # If we navigate to the base page, we show blank view (no items or branches) to obscure data from scientists
        if filter is None:
          #  item_tree = self.scan_directory("")
            item_tree = ItemTree("", [], [])
        # If we navigate to "admin" we show top level folders (no items) to provide links to sites for labs by admin and maintainers
        elif filter == "admin":
            item_tree = self.scan_directory("",top=True)
        # If we navigate to webpage, show all branches and items
        else:
            item_tree = self.scan_directory(filter)
        return item_tree
.
.
.
```python
def is_annotation_dir(dir):
            return (
                dir.endswith(self.annotation_dir_suffix)
                and self.convert_annotation_path_to_h5ad(dir) in h5ad_paths
            )

        h5ad_paths = [
            filepath
            for filepath, full_path in filepath_map.items()
            if self.is_h5ad_file(full_path)
        ]
        subdirs = [
            filepath
            for filepath, full_path in filepath_map.items()
                if os.path.isdir(full_path) and not is_annotation_dir(filepath)

        items = [
            self.make_fileitem_from_path(filename, subpath) for filename in h5ad_paths
        ]
        branches = None
        if len(subdirs) > 0:
            branches = [
               self.scan_directory(os.path.join(subpath, subdir)) for subdir in subdirs
            ]
        # If on admin page, make item list blank so that we only list available branches
        if top==True:
            return ItemTree(subpath, [], branches)
        else:
            return ItemTree(subpath, items, branches)

```

**Comment by Dane-Z** [comment]
Oh, and to hide the heading which has the "local: <directory>" link, we can simply comment out and modify these lines in the render_item_source function in filecrawl.py:

```
def render_item_source(item_source, filter=None):
    item_tree = item_source.list_items(filter)
    filterpart = "" if filter is None else ":" + filter
   # heading = f"<h6><a href='/filecrawl.html?source={urllib.parse.quote_plus(item_source.name)}'>{item_source.name}</a>{filterpart}</h6>"
    return render_item_tree(item_tree, item_source) #heading + 
```
