### ISSUE TITLE
Force refresh cellxgene instance for overwriting a file with same name 

### ISSUE THREAD

**Issue by Dane-Z** [Novartis/cellxgene-gateway#76]
Hello, we've run into an issue that's similar to issue #59. However, while the listing of files updates automatically, if we upload a h5ad file to a directory, launch a cellxgene instance, then realize that there's a mistake in the metadata, fix the issue and reupload/overwrite the h5ad file with the same name, we are not able to see those changes in the cellxgene instance until we restart the server. 

I think this is happening because of the backend caches that file instance name and relaunches the already running instance regardless of whether or not the file has been overwritten. Is there a way that we can refresh the cache if a file has been overwritten or prevent backend caching so that we don't run into this issue? 

Thank you so much for the help!!

**Comment by alokito** [comment]
Hi Dane! Just seeing this now. Cellxgene-gateway launches a separate instance of cellxgene for each dataset. The instance only loads the dataset once when it is launched. You can see a list of running servers by going to /cache_status, and click "terminate" to stop the running stance. 
![terminate](https://github.com/Novartis/cellxgene-gateway/assets/789030/5788461d-208e-4855-a157-91feacead05e)

**Comment by alokito** [comment]
Closing for now, but please reopen if I misunderstood the issue.
