### ISSUE TITLE
File crawler does not scale for deeply nested directories

### ISSUE THREAD

**Issue by aeisenbarth** [Novartis/cellxgene-gateway#78]
We have AnnData files stored together with other data which inherently use a deep folder hierarchy (Zarr). The file crawler successfully skips _files_ that are not `*.h5ad`, but _directories not containing h5ad_ are still rendered. This produces a huge tree.

![image](https://user-images.githubusercontent.com/54448967/195390282-274a0d40-7df7-4975-961a-3d18824edd4e.png)

## Solutions

- A possible solution would be to integrate a proper file browser web component that uses step-by-step navigation (progressive disclosure).
- Keeping the existing file crawler, it would help to also filter directories which have no h5ad as leaf.  
  (See #77)

**Comment by alokito** [comment]
This is deployed to pypi in v0.3.11, please open a new ticket if there are any remaining issues.
