### ISSUE TITLE
Issue with Docker implementation

### ISSUE THREAD

**Issue by streptomycin** [Novartis/cellxgene-gateway#86]
Hi,
First, thanks for putting such an amazing project together. On the behalf of the single cell community, thanks a lot 👍 

Here's the issue: I've tried to create an instance of cellxgene-gateway with Docker today and was having a recurrent error when pip was being called. After some debugging, I've noticed that the pip version that is called inside the Docker image python:3.9 is outdated. This was easily fixed by changing the Dockerfile line:
```
RUN pip install cellxgene-gateway 'MarkupSafe<2.1'
```
to this:
```
RUN pip install --upgrade pip \
    && pip install cellxgene-gateway 'MarkupSafe<2.1'
```

Hope this helps anyone that may be having the same issues. 👍

**Comment by alokito** [comment]
Thanks for the MR!
