### ISSUE TITLE
ImportError: cannot import name 'url_decode_stream' from 'werkzeug.urls' 

### ISSUE THREAD

**Issue by ahrweber** [Novartis/cellxgene-gateway#87]
I installed cellxgene-gateway using anaconda Python 3.11.5.

cellxgene-gateway does not start with error: 
# ImportError: cannot import name 'url_decode_stream' from 'werkzeug.urls' (/home/user/.cellxgene-gateway/lib/python3.11/site-packages/werkzeug/urls.py)

After search I got aware of some changes in flask version >= 3.0.

And the standard installation installed 
conda list | grep werkzeug
# werkzeug                  3.0.1                    pypi_0    pypi
conda list | grep flask
# flask                     3.0.1                    pypi_0    pypi

Solved the error by installing fix versions:
pip install werkzeug==2.3.0 flask==2.2.2

After that cellxgene-gateway starts and works fine.

**Comment by alokito** [comment]
I'll pin the versions for now. cellxgene-gateway is due for a cycle of dependency updates.

**Comment by alokito** [comment]
@ahrweber this issue should be addressed in cellxgene-gateway 0.4.0, please confirm if you have time.
