### ISSUE TITLE
UnicodeDecodeError leads to Internal Server Error

### ISSUE THREAD

**Issue by earsmcgee11** [Novartis/cellxgene-gateway#94]
Hi, 

So I have cellxgene-gateway set up, and can access the file crawler, but when I attempt to open a file I get an internal server error. Cellxgene says it is starting the CLI and loading data from my file but that's when the error pops up. My log is saying " utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte" which makes me think cellxgene-gateway is creating the wrong encoding for Werkzeug, but I could be wrong. I attached screenshots below. I am very new to cellxgene and cellxgene-gateway so please let me know if this is a mistake on my end. 
![error](https://github.com/user-attachments/assets/fe08c29b-5b4b-4268-a479-7d2278cf4fda)
![errorchrome](https://github.com/user-attachments/assets/a2c459d9-d238-47f7-bedb-dcc583db7274)

**Comment by earsmcgee11** [comment]
Never mind I figured it out

**Comment by eusebiu** [comment]
How did you solve it?
